<a href="https://colab.research.google.com/github/Kim-yongbeom/python_DB/blob/main/colab_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('welcome')

welcome


In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

In [ ]:
# 경로복사가능
pd.read_csv('/content/drive/MyDrive/Colab Notebooks/csv_data/01. CCTV_in_Seoul.csv')

기관명    소계  2013년도 이전  2014년  2015년  2016년
0    강남구  2780       1292    430    584    932
1    강동구   773        379     99    155    377
2    강북구   748        369    120    138    204
3    강서구   884        388    258    184     81
4    관악구  1496        846    260    390    613
5    광진구   707        573     78     53    174
6    구로구  1561       1142    173    246    323
7    금천구  1015        674     51    269    354
8    노원구  1265        542     57    451    516
9    도봉구   485        238    159     42    386
10  동대문구  1294       1070     23    198    579
11   동작구  1091        544    341    103    314
12   마포구   574        314    118    169    379
13  서대문구   962        844     50     68    292
14   서초구  1930       1406    157    336    398
15   성동구  1062        730     91    241    265
16   성북구  1464       1009     78    360    204
17   송파구   618        529     21     68    463
18   양천구  2034       1843    142     30    467
19  영등포구   904        495    214    195    373
20   용산구  1624       1368    218    112    398
21   은평구  1873       1138    224    278    468
22   종로구  1002        464    314    211    630
23    중구   671        413    190     72    348
24   중랑구   660        509    121    177    109

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df2 = pd.DataFrame({"name" : ["kim", "yong"],
                    "age" : [10,20],
                    })

In [ ]:
df2

name  age
0   kim   10
1  yong   20

In [ ]:
df2.index

RangeIndex(start=0, stop=2, step=1)

In [ ]:
df2.values

array([['kim', 10],
       ['yong', 20]], dtype=object)

In [ ]:
df2.name

0     kim
1    yong
Name: name, dtype: object

In [ ]:
df2['name']

0     kim
1    yong
Name: name, dtype: object

In [ ]:
df2.name.index

RangeIndex(start=0, stop=2, step=1)

In [ ]:
df2.name.values

array(['kim', 'yong'], dtype=object)

In [ ]:
# 언랩핑
df2.name.values.tolist()

['kim', 'yong']

In [ ]:
df3 = pd.DataFrame(data=[['hong',10],['park',20]], columns=['name','age'])

In [ ]:
df3

name  age
0  hong   10
1  park   20

In [ ]:
df3.dtypes

name    object
age      int64
dtype: object

In [ ]:
# 원본을 파괴시키지않는 비파괴 함수이다 astype은
df3['age'].astype(float)

0    10.0
1    20.0
Name: age, dtype: float64

In [ ]:
df3.dtypes

name    object
age      int64
dtype: object

In [ ]:
df3['age'] = df3['age'].astype(float)

In [ ]:
df3.dtypes

name     object
age     float64
dtype: object

In [ ]:
df3

name   age
0  hong  10.0
1  park  20.0

In [ ]:
df3['age'] = df3['age'].astype(int)

In [ ]:
df3

name  age
0  hong   10
1  park   20

In [ ]:
# 숫자형만 계산해줌
# 숫자여도 object이면 계산 안함
df3.describe()

age
count   2.000000
mean   15.000000
std     7.071068
min    10.000000
25%    12.500000
50%    15.000000
75%    17.500000
max    20.000000

In [ ]:
type(df3['name'])

pandas.core.series.Series

In [ ]:
df3['name']

0    hong
1    park
Name: name, dtype: object

In [ ]:
df3['name'].index

RangeIndex(start=0, stop=2, step=1)

In [ ]:
df3['name'].values

array(['hong', 'park'], dtype=object)

In [ ]:
type(df3['name'].values)

numpy.ndarray

In [ ]:
mask = np.zeros((3,4))

In [ ]:
mask

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
mask2 = np.zeros(5)

In [ ]:
mask2

array([0., 0., 0., 0., 0.])

In [ ]:
arr2 = np.array([
    [1,2,3],
    [4,5,6]
]
, dtype=np.float64)
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr3 = np.array([
    [7,8,9],
    [10,11,12]
]
, dtype=np.float64)
arr3

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [ ]:
arr2+arr3

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [ ]:
arr2*arr3

array([[ 7., 16., 27.],
       [40., 55., 72.]])