<a href="https://colab.research.google.com/github/Kim-yongbeom/machine-learning/blob/main/data16/vectorize_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [ ]:
corpus = [
          'you know I want your love',
          'I like you',
          'what should I do',
          'I hate you'
]

In [ ]:
vector = CountVectorizer()
print(vector.fit_transform(corpus).toarray()) # 빈도수 기록
print(vector.vocabulary_)
# {'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}
# value값은 인덱스 번호를 뜻한다 
# ex) 0번 인덱스는 do , do가 있는곳에는 1로 표시

[[0 0 1 0 1 0 1 0 1 1]
 [0 0 0 1 0 0 0 0 1 0]
 [1 0 0 0 0 1 0 1 0 0]
 [0 1 0 0 0 0 0 0 1 0]]
{'you': 8, 'know': 2, 'want': 6, 'your': 9, 'love': 4, 'like': 3, 'what': 7, 'should': 5, 'do': 0, 'hate': 1}


In [ ]:
cv = CountVectorizer()

In [ ]:
# 1. 사전을 만들어라!! -> fit()
# 2. 사전에 들어있는 id로 인코딩을 해라!! -> tranform()
# 3. 1,2를 함께 처리하고자 하는 경우는 -> fit_transform()

In [ ]:
cv.fit_transform(corpus)

<4x10 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [ ]:
cv.fit_transform(corpus).toarray()

array([[0, 0, 1, 0, 1, 0, 1, 0, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 1, 0]])

In [ ]:
cv.vocabulary_

{'do': 0,
 'hate': 1,
 'know': 2,
 'like': 3,
 'love': 4,
 'should': 5,
 'want': 6,
 'what': 7,
 'you': 8,
 'your': 9}

In [ ]:
tfidf = TfidfVectorizer()

In [ ]:
# fit --> transform

In [ ]:
tfidf.fit_transform(corpus)

<4x10 sparse matrix of type '<class 'numpy.float64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [ ]:
tfidf.fit_transform(corpus).toarray()

array([[0.        , 0.        , 0.47633035, 0.        , 0.47633035,
        0.        , 0.47633035, 0.        , 0.30403549, 0.47633035],
       [0.        , 0.        , 0.        , 0.84292635, 0.        ,
        0.        , 0.        , 0.        , 0.53802897, 0.        ],
       [0.57735027, 0.        , 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.57735027, 0.        , 0.        ],
       [0.        , 0.84292635, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.53802897, 0.        ]])

In [ ]:
print(tfidf.vocabulary_)

{'you': 8, 'know': 2, 'want': 6, 'your': 9, 'love': 4, 'like': 3, 'what': 7, 'should': 5, 'do': 0, 'hate': 1}


In [ ]:
sentence = ['i like like like hate smile']

In [ ]:
nd2array = cv.transform(sentence).toarray()
nd2array

array([[0, 1, 0, 3, 0, 0, 0, 0, 0, 0]])

In [ ]:
nd2array[0]

array([0, 1, 0, 3, 0, 0, 0, 0, 0, 0])

In [ ]:
nd2array = tfidf.transform(sentence).toarray()
nd2array

array([[0.        , 0.31622777, 0.        , 0.9486833 , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [ ]:
cv.inverse_transform(nd2array)

[array(['hate', 'like'], dtype='<U6')]

In [ ]:
tfidf.inverse_transform(nd2array)

[array(['hate', 'like'], dtype='<U6')]

In [ ]:
feature_list = cv.get_feature_names() # 사전에 무엇이 들어있는지 확인
feature_list

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['do', 'hate', 'know', 'like', 'love', 'should', 'want', 'what', 'you', 'your']

In [ ]:
# dic <--- list
dictionary = dict()
for index, value in enumerate(feature_list):
  dictionary[index] = value
dictionary

{0: 'do',
 1: 'hate',
 2: 'know',
 3: 'like',
 4: 'love',
 5: 'should',
 6: 'want',
 7: 'what',
 8: 'you',
 9: 'your'}

In [ ]:
## 스팸을 나타내는 사전을 만들어 주세요
## 스팸이 아닌 사전을 만들어 주세요

In [ ]:
## 광고!! 짱 좋은 판매 홍보전략입니다.!! -> 스팸

In [ ]:
spam_dict = ["advertise", "promotion", "sales", "hu", "special", "sale","member", "company"]

In [ ]:
ham_dict = ["order", "confirm", "check", "customer", "payment", "send", "general", "club"]

In [ ]:
spam_fit = cv.fit(spam_dict)

In [ ]:
spam_fit.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['advertise',
 'company',
 'hu',
 'member',
 'promotion',
 'sale',
 'sales',
 'special']

In [ ]:
spam_fit.vocabulary_

{'advertise': 0,
 'company': 1,
 'hu': 2,
 'member': 3,
 'promotion': 4,
 'sale': 5,
 'sales': 6,
 'special': 7}

In [ ]:
email = ['promotion!! hu good sales.!! check payment']

In [ ]:
email_spam_array = spam_fit.transform(email).toarray()
email_spam_array

array([[0, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
ham_fit = cv.fit(ham_dict)

In [ ]:
ham_fit.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['check', 'club', 'confirm', 'customer', 'general', 'order', 'payment', 'send']

In [ ]:
ham_fit.vocabulary_

{'check': 0,
 'club': 1,
 'confirm': 2,
 'customer': 3,
 'general': 4,
 'order': 5,
 'payment': 6,
 'send': 7}

In [ ]:
email_ham_array = ham_fit.transform(email).toarray()
email_ham_array

array([[1, 0, 0, 0, 0, 0, 1, 0]])

In [ ]:
spam_dict2 = ["광고", "홍보", "판매", "허경영", "특가", "세일","회원", "회사"]
ham_dict2 = ["주문", "확인", "체크", "고객", "지불", "배송", "일반", "동호회"]

In [ ]:
cv2 = CountVectorizer()

In [ ]:
cv2.fit(spam_dict2)

CountVectorizer()

In [ ]:
email2 = ['광고!! 허경영 짱 좋은 세일 확인 지불']

In [ ]:
result = cv2.transform(email2).toarray()
result

array([[1, 1, 0, 0, 1, 0, 0, 0]])

In [ ]:
result_count1 = 0
for i in result[0]:
  result_count1 += i
result_count1

3

In [ ]:
cv2.fit(ham_dict2)

CountVectorizer()

In [ ]:
result1 = cv2.transform(email2).toarray()
result1

array([[0, 0, 0, 0, 0, 1, 0, 1]])

In [ ]:
result_count2 = 0
for i in result1[0]:
  result_count2 += i
result_count2

2

In [ ]:
## 감정분류기
# 긍정/부정 사전을 만들어 보세요.
# input() 이용해서, 문장을 받으면, 그것이 긍정인지 부정인지 판단해보세요.
# if-idf vectorizer를 사용해주세요.

In [ ]:
!pip install konlpy

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from konlpy.tag import Okt
okt = Okt()

In [ ]:
neg = [
          '슬픔', '눈물', '바보', '멍충이'
]

pos = [
       '기쁘다', '행복', '웃음', '즐거움'
]

In [ ]:
talk = [input()]

슬픔 눈물 기쁘다 바보야


In [ ]:
vector = CountVectorizer()
tfidf = TfidfVectorizer()

In [ ]:
tfidf.fit(neg)

TfidfVectorizer()

In [ ]:
result = tfidf.transform(talk).toarray()
result

array([[0.70710678, 0.        , 0.        , 0.70710678]])

In [ ]:
result_neg_count = 0
for i in result[0]:
  result_neg_count += i
result_neg_count

1.4142135623730951

In [ ]:
if result_neg_count > 1:
  print('부정')
else:
  print('긍정')

부정
