<a href="https://colab.research.google.com/github/Kim-yongbeom/python_DB/blob/main/data04/%EC%82%AC%EC%9D%B4%ED%82%B7%EB%9F%B0%EC%9D%84_%ED%86%B5%ED%95%9C_%EC%95%84%EC%9D%B4%EB%A6%AC%EC%8A%A4_%ED%92%88%EC%A2%85_%EB%B6%84%EB%A5%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris_data = load_iris()

In [4]:
iris_data

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [5]:
iris_data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [6]:
iris_data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
iris_data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
iris_data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [9]:
iris_data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
iris_data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
iris_data.target.shape

(150,)

In [12]:
iris_data.data.shape

(150, 4)

In [14]:
import pandas as pd
import numpy as np

In [15]:
# 데이터 프레임에 넣어라
# 데이터, 컬럼명
df = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)

In [16]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [17]:
df['target'] = iris_data.target
df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                  5.1               3.5  ...               0.2       0
1                  4.9               3.0  ...               0.2       0
2                  4.7               3.2  ...               0.2       0
3                  4.6               3.1  ...               0.2       0
4                  5.0               3.6  ...               0.2       0
..                 ...               ...  ...               ...     ...
145                6.7               3.0  ...               2.3       2
146                6.3               2.5  ...               1.9       2
147                6.5               3.0  ...               2.0       2
148                6.2               3.4  ...               2.3       2
149                5.9               3.0  ...               1.8       2

[150 rows x 5 columns]

In [20]:
df.rename(columns={'sepal length (cm)':'sepal length', 'sepal width (cm)':'sepal width', 'petal length (cm)':'petal length','petal width (cm)':'petal width'}, inplace=True)

In [21]:
df

sepal length  sepal width  petal length  petal width  target
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]

In [22]:
df.columns

Index(['sepal length', 'sepal width', 'petal length', 'petal width', 'target'], dtype='object')

In [26]:
# 공부할 데이터와 테스트용 데이터를 분리
from sklearn.model_selection import train_test_split

In [28]:
x_data = df.loc[:, 'sepal length':'petal width'] # 문제데이터
y_data = df.loc[:, 'target'] # 정답데이터

In [29]:
x_train, x_test, y_train, y_test = train_test_split(
    x_data, # 문제 데이터
    y_data, # 답 데이터
    test_size =0.2, # 비율
    shuffle = True, # 셔플링 여부
    random_state = 20 # 시드값
)

In [30]:
# x는 문제
# train은 교육시키는것
x_train.shape

(120, 4)

In [32]:
# test는 모의고사
x_test.shape

(30, 4)

In [33]:
# y는 답
y_train.shape

(120,)

In [35]:
y_test.shape

(30,)

In [44]:
# 공부방법론을 정해서 공부를 시키자
from sklearn.neighbors import KNeighborsClassifier

In [77]:
knn = KNeighborsClassifier(n_neighbors=5) # 하이퍼파라메터 (내가 조절할 수 있는 파라메터)

In [78]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [79]:
# 테스트용 데이터로 점수가 얼마나 나오는지 검증해보기
pred = knn.predict(x_test)
pred

array([0, 1, 1, 2, 1, 1, 2, 0, 2, 0, 2, 1, 2, 0, 0, 2, 0, 1, 2, 1, 1, 2,
       2, 0, 2, 1, 1, 0, 2, 2])

In [80]:
# 모의고사 점수가 얼마나 나왔는지 확인을 해보자 -> 채점
from sklearn.metrics import accuracy_score

In [81]:
# 1이 나오면 안됨 적당히 떨궈주자
jumsu = accuracy_score(y_test, pred) # 원래정답, 내가푼답
jumsu # accuracy

0.9666666666666667

In [82]:
from sklearn.svm import SVC

In [83]:
svc = SVC(kernel='rbf')

In [84]:
svc.fit(x_train, y_train)

SVC()

In [85]:
pred2 = svc.predict(x_test)
pred2

array([0, 1, 1, 2, 1, 1, 2, 0, 2, 0, 2, 1, 2, 0, 0, 2, 0, 1, 2, 1, 1, 2,
       2, 0, 1, 1, 1, 0, 2, 2])

In [86]:
jumsu2 = accuracy_score(y_test, pred2)
jumsu2

1.0

In [112]:
from sklearn.datasets import load_wine

In [120]:
wine = load_wine()
wine

{'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:           

In [116]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [119]:
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0      14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1      13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2      13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3      14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4      13.24        2.59  2.87  ...  1.04                          2.93    735.0
..       ...         ...   ...  ...   ...                           ...      ...
173    13.71        5.65  2.45  ...  0.64                          1.74    740.0
174    13.40        3.91  2.48  ...  0.70                          1.56    750.0
175    13.27        4.28  2.26  ...  0.59                          1.56    835.0
176    13.17        2.59  2.37  ...  0.60                          1.62    840.0
177    14.13        4.10  2.74  ...  0.61                          1.60    560.0

[178 rows x 13 columns]

In [121]:
df['target'] = wine.target
df

alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  target
0      14.23        1.71  2.43  ...                          3.92   1065.0       0
1      13.20        1.78  2.14  ...                          3.40   1050.0       0
2      13.16        2.36  2.67  ...                          3.17   1185.0       0
3      14.37        1.95  2.50  ...                          3.45   1480.0       0
4      13.24        2.59  2.87  ...                          2.93    735.0       0
..       ...         ...   ...  ...                           ...      ...     ...
173    13.71        5.65  2.45  ...                          1.74    740.0       2
174    13.40        3.91  2.48  ...                          1.56    750.0       2
175    13.27        4.28  2.26  ...                          1.56    835.0       2
176    13.17        2.59  2.37  ...                          1.62    840.0       2
177    14.13        4.10  2.74  ...                          1.60    560.0       2

[178 rows x 14 columns]

In [122]:
# 공부할 데이터와 테스트용 데이터를 분리
from sklearn.model_selection import train_test_split

In [191]:
x_data = df.loc[:, 'alcohol':'proline'] # 문제데이터
y_data = df.loc[:, 'target'] # 정답데이터

In [192]:
x_train, x_test, y_train, y_test = train_test_split(
    x_data, # 문제 데이터
    y_data, # 답 데이터
    test_size =0.2, # 비율
    shuffle = True, # 셔플링 여부
    random_state = 20 # 시드값
)

In [193]:
x_train

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
1      13.20        1.78  2.14  ...  1.05                          3.40   1050.0
67     12.37        1.17  1.92  ...  1.12                          3.48    510.0
174    13.40        3.91  2.48  ...  0.70                          1.56    750.0
64     12.17        1.45  2.53  ...  1.45                          2.23    355.0
20     14.06        1.63  2.28  ...  1.09                          3.71    780.0
..       ...         ...   ...  ...   ...                           ...      ...
148    13.32        3.24  2.38  ...  0.55                          1.62    650.0
137    12.53        5.51  2.64  ...  0.82                          1.69    515.0
156    13.84        4.12  2.38  ...  0.57                          1.64    480.0
15     13.63        1.81  2.70  ...  1.28                          2.88   1310.0
99     12.29        3.17  2.21  ...  1.42                          2.83    406.0

[142 rows x 13 columns]

In [194]:
x_test

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
111    12.52        2.43  2.17  ...  0.90                          2.78    325.0
177    14.13        4.10  2.74  ...  0.61                          1.60    560.0
46     14.38        3.59  2.28  ...  1.04                          3.44   1065.0
112    11.76        2.68  2.92  ...  1.23                          2.50    607.0
91     12.00        1.51  2.42  ...  1.05                          2.65    450.0
72     13.49        1.66  2.24  ...  0.98                          2.78    472.0
140    12.93        2.81  2.70  ...  0.77                          2.31    600.0
107    12.72        1.75  2.28  ...  0.88                          2.42    488.0
125    12.07        2.16  2.17  ...  0.86                          3.28    378.0
169    13.40        4.60  2.86  ...  0.67                          1.92    630.0
47     13.90        1.68  2.12  ...  0.91                          3.33    985.0
165    13.73        4.36  2.26  ...  0.78                          1.75    520.0
120    11.45        2.40  2.42  ...  0.80                          3.39    625.0
62     13.67        1.25  1.92  ...  1.23                          2.46    630.0
13     14.75        1.73  2.39  ...  1.25                          2.73   1150.0
92     12.69        1.53  2.26  ...  0.96                          2.06    495.0
87     11.65        1.67  2.62  ...  1.36                          3.21    562.0
28     13.87        1.90  2.80  ...  1.25                          3.40    915.0
51     13.83        1.65  2.60  ...  1.24                          3.37   1265.0
155    13.17        5.19  2.32  ...  0.60                          1.48    725.0
161    13.69        3.26  2.54  ...  0.96                          1.82    680.0
44     13.05        1.77  2.10  ...  0.88                          3.35    885.0
124    11.87        4.31  2.39  ...  0.75                          3.64    380.0
34     13.51        1.80  2.65  ...  1.10                          2.87   1095.0
132    12.81        2.31  2.40  ...  0.66                          1.36    560.0
77     11.84        2.89  2.23  ...  0.96                          2.52    500.0
45     14.21        4.04  2.44  ...  0.87                          3.33   1080.0
136    12.25        4.72  2.54  ...  0.75                          1.27    720.0
80     12.00        0.92  2.00  ...  1.38                          3.12    278.0
103    11.82        1.72  1.88  ...  0.94                          2.44    415.0
68     13.34        0.94  2.36  ...  1.02                          1.93    750.0
109    11.61        1.35  2.70  ...  0.96                          3.26    680.0
152    13.11        1.90  2.75  ...  0.61                          1.33    425.0
100    12.08        2.08  1.70  ...  1.27                          2.96    710.0
12     13.75        1.73  2.41  ...  1.15                          2.90   1320.0
55     13.56        1.73  2.46  ...  0.98                          3.03   1120.0

[36 rows x 13 columns]

In [195]:
y_train

1      0
67     1
174    2
64     1
20     0
      ..
148    2
137    2
156    2
15     0
99     1
Name: target, Length: 142, dtype: int64

In [199]:
knn = KNeighborsClassifier(n_neighbors=9)

In [200]:
knn.fit(x_train,y_train)
pred = knn.predict(x_test)
pred

array([1, 2, 0, 2, 1, 1, 2, 1, 1, 2, 0, 1, 2, 2, 0, 1, 2, 0, 0, 2, 2, 0,
       1, 0, 2, 2, 0, 2, 1, 1, 0, 1, 1, 2, 0, 0])

In [201]:
jumsu = accuracy_score(y_test, pred) # 원래정답, 내가푼답
jumsu # accuracy

0.75

In [205]:
# svc kernel 종류 찾아보기
svc = SVC(kernel='linear')
svc.fit(x_train, y_train)

SVC(kernel='linear')

In [206]:
pred2 = svc.predict(x_test)
pred2

array([1, 2, 0, 1, 1, 1, 2, 1, 1, 2, 0, 2, 1, 1, 0, 1, 1, 0, 0, 2, 2, 0,
       1, 0, 2, 1, 0, 2, 1, 1, 0, 1, 2, 1, 0, 0])

In [207]:
jumsu2 = accuracy_score(y_test, pred2)
jumsu2

0.9722222222222222